### ISSUE TITLE
MQTT with SSL 지원

### ISSUE THREAD

**Issue by saya6k** [iluna8/ha-addons#2]
혹시 MQTT with SSL이 지원되나요? 지원이 안된다면 업데이트해주실 수 있는지도 궁금합니다!

**Comment by lunDreame** [comment]
어떤 애드온 말씀인가요?

**Comment by saya6k** [comment]
아 죄송합니다! 이지롤입니다

**Comment by lunDreame** [comment]
MQTT SSL 기능 추가했습니다. 설정 방법은 EasyRoll Smart Blind 관련문서 탭에 적어놨습니다. 버전은 1.9그대로이고(파일만 업데이트) 테스트해보신 후 문제가 없다면 업데이트하도록 하겠습니다.

**Comment by saya6k** [comment]
잘 되는것 같아요!
